version: 2.1
jobs:
  build:
      docker:
        - image: cibuilds/hugo:latest
      working_directory: ~/workers-safety-website
      environment: 
          HUGO_BUILD_DIR: ~/workers-safety-website/public
      steps:
         # install git
        - run: sudo apt-get update && sudo apt-get install git
        - checkout
        
        - run:
            name: "Install AWS CLI( first install pip, the python package manager)"
            command: sudo apt-get install awscli

        # build with Hugo      
        - run:
            name: "Run Hugo"
            command: HUGO_ENV=production hugo -v -d ~/workers-safety-website/public
        
       
        # Deploy
  
        - deploy:
            name: deploy to AWS
            command: |
                if [[ "${CIRCLE_BRANCH}" == "test-1" ]]; then
                     aws s3 sync public/ s3://workers-safety.ca/          
                  else
                    echo "Not master branch, dry run only"
                fi

workflows:
  version: 2.1
  main:
    jobs:
      - build:
          filters:
            branches:
              only: test-1
