version: 2.1
jobs:
  build:
      docker:
        - image: cibuilds/hugo:latest
      working_directory: ~/mysite
      environment: 
          HUGO_BUILD_DIR: ~/mysite/public
      steps:
        - checkout
        
        - run:
            name: "Install AWS CLI( first install pip, the python package manager)"
            command: sudo apt-get install awscli

        # build with Hugo      
        - run: 
            name: "Staging Environment"
            command: HUGO_ENV=staging hugo -v -d ~/mysite/public --baseUrl=http://stage.workers-safety.ca/ 
            
        - run:
            name: "Production Environment"
            command: HUGO_ENV=production hugo -v -d ~/mysite/public --baseUrl=http://workers-safety.ca/
        
       
        # Deploy
  
        - deploy:          
            name: deploy to Production
            command: |
                if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
                    # aws s3 rm s3://workers-safety.ca/ --recursive
                    # aws s3 sync public/ s3:///workers-safety.ca/ 
                  else
                    echo "Not master branch, dry run only"
                fi
                
        - deploy: 
            name: deploy to staging
            command: |
                if [[ "${CIRCLE_BRANCH}" == "test-1"]]; then
                    # aws s3 rm s3://workers-safety.ca/ --recursive
                    # aws s3 sync public/ s3://stage./workers-safety.ca/           
                  else
                    echo "Not master branch, dry run only"
                fi
                
workflows:
  version: 2
  staging:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
                - test-1
