---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content/features
  label: Features
  create: all
  match: "**/*"
- type: directory
  path: content/menu
  label: Menu
  create: all
  match: "**/*"
- type: directory
  path: content/communications
  label: Communications
  create: all
  match: "**/*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: static/img/banners
public_path: img/banners
front_matter_path: img/banners
use_front_matter_path: false
file_template: ":filename:"
version: '0.17'
